// Raw questions: https://improb.com/would-you-rather-questions/
// Questions Sheet: https://docs.google.com/spreadsheets/d/1676JAQM8-DWPV5Fc4gyQE5OBC2C1u2Ay0wbZ927lqZU/edit#gid=0

export const stubQuestions = [
  {
    id: 1,
    optionA: 'have 3 feet',
    optionB: '3 hands',
    frequencyA: 94,
    frequencyB: 6,
  },
  {
    id: 2,
    optionA: 'have all your shirts be 2 sizes too big',
    optionB: 'have all of them be 1 size too small',
    frequencyA: 62,
    frequencyB: 38,
  },
  {
    id: 3,
    optionA: 'lose your sense of taste',
    optionB: 'your sense of smell',
    frequencyA: 67,
    frequencyB: 33,
  },
  {
    id: 4,
    optionA: 'only be able to whisper',
    optionB: 'only be able to shout',
    frequencyA: 29,
    frequencyB: 71,
  },
  {
    id: 5,
    optionA: 'live the rest of your life with silent, but uncontrollable gas',
    optionB: 'loud, uncontrollable sneezing',
    frequencyA: 46,
    frequencyB: 54,
  },
  {
    id: 6,
    optionA: 'be able to freeze time',
    optionB: 'travel in time',
    frequencyA: 49,
    frequencyB: 51,
  },
  {
    id: 7,
    optionA: 'live without music',
    optionB: 'without television',
    frequencyA: 11,
    frequencyB: 89,
  },
  {
    id: 8,
    optionA: 'know how you are going to die',
    optionB: 'when you are going to die',
    frequencyA: 14,
    frequencyB: 86,
  },
  {
    id: 9,
    optionA: 'have your dream job',
    optionB: 'find your true love',
    frequencyA: 24,
    frequencyB: 76,
  },
  {
    id: 10,
    optionA: 'wrestle a bear',
    optionB: 'an alligator',
    frequencyA: 100,
    frequencyB: 0,
  },
  {
    id: 11,
    optionA: 'only be able to speak in rhyme',
    optionB: 'only be able to speak using alliteration',
    frequencyA: 27,
    frequencyB: 73,
  },
  {
    id: 12,
    optionA: 'be trapped in a small room with 10,000 tarantulas for 10 minutes',
    optionB: 'eat 10 tarantulas in 10 minutes',
    frequencyA: 77,
    frequencyB: 23,
  },
  {
    id: 13,
    optionA: 'lose all of your teeth',
    optionB: 'all of your hair',
    frequencyA: 100,
    frequencyB: 0,
  },
  {
    id: 14,
    optionA: 'never be able to wear makeup again',
    optionB:
      'never be able to leave the house without a full face of makeup, but you can only use kids’ makeup',
    frequencyA: 90,
    frequencyB: 10,
  },
  {
    id: 15,
    optionA: 'have the ability to read people’s minds',
    optionB: 'make two people fall in love',
    frequencyA: 91,
    frequencyB: 9,
  },
  {
    id: 16,
    optionA: 'be able to run as fast as a cheetah',
    optionB: 'fly, but only as fast as a tortoise',
    frequencyA: 71,
    frequencyB: 29,
  },
  {
    id: 17,
    optionA: 'have a permanent splinter under your big toenail',
    optionB: 'have a permanent bad haircut',
    frequencyA: 53,
    frequencyB: 47,
  },
  {
    id: 18,
    optionA: 'read the book',
    optionB: 'watch the movie',
    frequencyA: 69,
    frequencyB: 31,
  },
  {
    id: 19,
    optionA: 'forget who you are every time it rains',
    optionB: 'never be able to remember why you walked into a room',
    frequencyA: 20,
    frequencyB: 80,
  },
  {
    id: 20,
    optionA: 'have to dress all in bright orange',
    optionB: 'all in lime green for the rest of your life',
    frequencyA: 52,
    frequencyB: 48,
  },
]
