// Raw questions: https://improb.com/would-you-rather-questions/
// Questions Sheet: https://docs.google.com/spreadsheets/d/1676JAQM8-DWPV5Fc4gyQE5OBC2C1u2Ay0wbZ927lqZU/edit#gid=0

export const stubQuestions = [
  {
    id: 0,
    optionA: 'Have 3 feet',
    optionB: '3 hands',
    frequencyA: 65,
    frequencyB: 35,
  },
  {
    id: 1,
    optionA: 'Have all your shirts be 2 sizes too big',
    optionB: 'Have all of them be 1 size too small',
    frequencyA: 44,
    frequencyB: 56,
  },
  {
    id: 2,
    optionA: 'Lose your sense of taste',
    optionB: 'Your sense of smell',
    frequencyA: 10,
    frequencyB: 90,
  },
  {
    id: 3,
    optionA: 'Only be able to whisper',
    optionB: 'Only be able to shout',
    frequencyA: 71,
    frequencyB: 29,
  },
  {
    id: 4,
    optionA: 'Live the rest of your life with silent, but uncontrollable gas',
    optionB: 'Loud, uncontrollable sneezing',
    frequencyA: 91,
    frequencyB: 9,
  },
  {
    id: 5,
    optionA: 'Be able to freeze time',
    optionB: 'Travel in time',
    frequencyA: 91,
    frequencyB: 9,
  },
  {
    id: 6,
    optionA: 'Live without music',
    optionB: 'Without television',
    frequencyA: 18,
    frequencyB: 82,
  },
  {
    id: 7,
    optionA: 'Know how you are going to die',
    optionB: 'When you are going to die',
    frequencyA: 92,
    frequencyB: 8,
  },
  {
    id: 8,
    optionA: 'Have your dream job',
    optionB: 'Find your true love',
    frequencyA: 25,
    frequencyB: 75,
  },
  {
    id: 9,
    optionA: 'Wrestle a bear',
    optionB: 'An alligator',
    frequencyA: 23,
    frequencyB: 77,
  },
  {
    id: 10,
    optionA: 'Only be able to speak in rhyme',
    optionB: 'Only be able to speak using alliteration',
    frequencyA: 19,
    frequencyB: 81,
  },
  {
    id: 11,
    optionA: 'Be trapped in a small room with 10,000 tarantulas for 10 minutes',
    optionB: 'Eat 10 tarantulas in 10 minutes',
    frequencyA: 45,
    frequencyB: 55,
  },
  {
    id: 12,
    optionA: 'Lose all of your teeth',
    optionB: 'All of your hair',
    frequencyA: 60,
    frequencyB: 40,
  },
  {
    id: 13,
    optionA: 'Never be able to wear makeup again',
    optionB:
      'Never be able to leave the house without a full face of makeup, but you can only use kids’ makeup',
    frequencyA: 10,
    frequencyB: 90,
  },
  {
    id: 14,
    optionA: 'Have the ability to read people’s minds',
    optionB: 'Make two people fall in love',
    frequencyA: 59,
    frequencyB: 41,
  },
  {
    id: 15,
    optionA: 'Be able to run as fast as a cheetah',
    optionB: 'Fly, but only as fast as a tortoise',
    frequencyA: 47,
    frequencyB: 53,
  },
  {
    id: 16,
    optionA: 'Have a permanent splinter under your big toenail',
    optionB: 'Have a permanent bad haircut',
    frequencyA: 34,
    frequencyB: 66,
  },
  {
    id: 17,
    optionA: 'Read the book',
    optionB: 'Watch the movie',
    frequencyA: 89,
    frequencyB: 11,
  },
  {
    id: 18,
    optionA: 'Forget who you are every time it rains',
    optionB: 'Never be able to remember why you walked into a room',
    frequencyA: 22,
    frequencyB: 78,
  },
  {
    id: 19,
    optionA: 'Have to dress all in bright orange',
    optionB: 'All in lime green for the rest of your life',
    frequencyA: 2,
    frequencyB: 98,
  },
]
